mysite/mycharts/urls.py
from django.urls import path

from . import views

app_name ='mycharts'
urlpatterns = [
    path('', views.index, name='index'),
    path('drawtable/', views.drawtable_detail, name='drawtable'),
    path('update/', views.update_table_data, name='update_table_data'),
    path('search/', views.searchtable, name='searchtable'),
    path('ui/', views.update_index, name='ui'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('doonce/', views.do_once, name='do_once'),
    path('restTest/', views.RESTfulTest.as_view(), name='restTest')


]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include
from django.conf.urls.static import static

from .settings import MEDIA_ROOT, MEDIA_URL, STATIC_ROOT, STATIC_URL

from django.urls import re_path
import re
from django.views.static import serve
from .views import index, favicon, error_404, error_500

# urlpatterns = [
#     path('polls/', include('polls.urls')),
#     path('admin/', admin.site.urls),
#     re_path(r'^%s(?P<path>.*)$' % re.escape(MEDIA_URL.lstrip('/')), serve, kwargs={'document_root': '%s' % MEDIA_ROOT}),
#
# ]
urlpatterns = [
    path('favicon.ico', favicon),
    path('', index),
    path('polls/', include('polls.urls')),
    path('mycharts/', include('mycharts.urls'), name='mycharts'),
    path('admin/', admin.site.urls),
    re_path(r'^%s(?P<path>.*)$' % re.escape(STATIC_URL.lstrip('/')), serve,
            {'document_root': STATIC_ROOT})

]

# def my_static(prefix, view=serve, **kwargs):
#     """
#     Return a URL pattern for serving files in debug mode.
#
#     from django.conf import settings
#     from django.conf.urls.my_static import my_static
#
#     urlpatterns = [
#         # ... the rest of your URLconf goes here ...
#     ] + my_static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     """
#     if not prefix:
#         raise ImproperlyConfigured("Empty my_static prefix not permitted")
#     elif not settings.DEBUG or urlsplit(prefix).netloc:
#         # No-op if not in debug mode or a non-local prefix.
#         return []
#     return [
#         re_path(r'^%s(?P<path>.*)$' % re.escape(prefix.lstrip('/')), view, kwargs=kwargs),
#     ]
handler404 = error_404
handler500 = error_500

mysite/polls/urls.py
from django.urls import path

from . import views

app_name ='polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('hello/', views.hello, name='hello'),
    path('touch/', views.touch, name='touch'),
    path('logout/', views.logout, name='logout'),
    path('info/', views.user_info, name='info'),
    # ex: /polls/5/
    path('<int:question_id>/', views.Detail.as_view(), name='detail'),
    path('drawing/', views.beforeDrawing, name='beforeDrawing'),
    path('drawing/<int:question_id>', views.Drawing.as_view(), name='drawing'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'), Detail 类视图替代
    path('login/', views.Login.as_view(), name='login'),
    path('register/', views.Register.as_view(), name='register'),

]

mysite/mycharts/models.py
from django.db import models


class TableData(models.Model):
    table_id = models.AutoField(primary_key=True)
    table_name = models.CharField(max_length=50)
    table_data = models.JSONField()

    def __str__(self):
        return self.table_name

    class Meta:
        ordering = ['table_id']


class TableDependence(models.Model):
    table_id = models.AutoField(primary_key=True)
    table_name = models.CharField(max_length=100)
    dependence = models.CharField(max_length=10000)

    def __str__(self):
        return self.table_name

mysite/mycharts/views.py
import datetime
import os
import sys
import time

from django.shortcuts import render, redirect, reverse, get_object_or_404
# render_to_response（）已弃用，取而代之的是render（）
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import TableData, TableDependence
from polls.models import User
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from pyecharts import charts
import pyecharts.options as opts
from pyecharts.globals import ThemeType
from .authenticated import is_authenticated, class_method_authenticated
from .excel_data_generator import getData, get_dep
import json

app_dir = os.path.dirname(__file__)


# project_dir =os.path.dirname(BaseDir)


class Login(View):
    """curl localhost:8000/mycharts/login/
        -F user=z -F passwd=123
        -H "X-CSRFtoken:[the value]"
        -b "csrftoken=[the same as above]"
    """

    def get(self, request):
        user = request.session.get('user', None)
        referer = request.session.get('HTTP_REFERER', '')

        if user:
            if referer:
                return HttpResponseRedirect(referer)
            else:
                return HttpResponseRedirect(reverse('mycharts:index'))
        return render(request, 'mycharts/login.html')

    def post(self, request):
        user_name = request.POST.get('user', None)
        passwd = request.POST.get('passwd', None)
        referer = request.session.get('HTTP_REFERER', '')
        print('login post :' + referer)
        try:
            user = User.objects.get(name=user_name)
            u_passwd = user.passwd
        except Exception as e:
            user = None
            u_passwd = None
        print('POST user:%s' % user)

        if user is not None and passwd == u_passwd:
            request.session.set_expiry(0)  # 关闭浏览器失效
            request.session['user'] = user_name
            request.session['passwd'] = passwd
            if referer:
                request.session['HTTP_REFERER'] = ''
                return HttpResponseRedirect(referer)
            else:
                return HttpResponseRedirect(reverse('mycharts:index'))
            # return render(request, 'index.html', {'name': request.session.get('user')})
        else:
            return HttpResponseRedirect(reverse('mycharts:login'))


@csrf_exempt
def logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('mycharts:login'))


@is_authenticated
# @csrf_exempt
def index(request):
    user = request.session.get('user')
    table_name = TableData.objects.filter(table_id__lte=10, table_id__gte=0).values('table_name')

    return render(request, 'mycharts/index.html', {'tables': table_name, 'name': user})


@is_authenticated
def searchtable(request):
    if request.method == 'GET':
        return HttpResponse('登录成功了，返回吧。这个页面还没做')
    # time.sleep(0.1)  # 测试前端用户感知，测试结束去掉
    json_data = request.body.decode('utf-8')
    info = json.loads(json_data)
    find_str = info.get('find_str', '')
    current_page = info.get('pn', 1)
    # table_names = TableData.objects.filter(table_name__contains=find_str).values('table_name')[:10]
    table_names = TableData.objects.filter(table_name__contains=find_str).order_by('table_id').values('table_name')
    paginator = Paginator(table_names, 10)  # Paginator生成一个对象，然后传入queryset,
    try:  # 以及每页显示的个数，这里每页显示十个
        page_obj = paginator.page(current_page)  # 根据get方法取到的数字显示页数
    except EmptyPage as e:  # 如果get方法获取了一个没有的页数则显示第一页
        page_obj = paginator.page(1)
    except PageNotAnInteger as e:  # 传入一个字符串也显示第一页
        page_obj = paginator.page(1)
    pagerange = paginator.get_elided_page_range(current_page, on_each_side=3, on_ends=2)
    page_obj.my_page_range = pagerange

    return render(request, 'mycharts/searchresult.html', {'tables': table_names, 'page_obj': page_obj})


@is_authenticated
def update_index(request):
    return render(request, 'mycharts/update.html')


@is_authenticated
def update_table_data(request):
    try:
        mk_day_data = getData(file_name=r'D:\bigdata\集中化搬迁\开发区svn文件\集中化数据核对\核对清单\aaa_mk日模型核对情况-整体.xlsx')
        dis_day_data = getData(file_name=r'D:\bigdata\集中化搬迁\开发区svn文件\集中化数据核对\核对清单\ccc_dis日表整体核对情况.xlsx')
        mk_mon_data = getData(file_name=r'D:\bigdata\集中化搬迁\开发区svn文件\集中化数据核对\核对清单\bbb_mk月模型核对情况-整体.xlsx',
                              sheet_name='mk月模型差异清单指标级', date_format='month')
        data = {**mk_day_data, **mk_mon_data, **dis_day_data}
        sixtyDaysAgo = (datetime.datetime.now() - datetime.timedelta(days=60)).strftime('%Y-%m-%d')
        for key, v in data.items():
            table = TableData.objects.get(table_name=key) if TableData.objects.filter(table_name=key) else TableData(
                table_name=key, table_data=dict())
            # 获取需要更新的最大最小账期 min_day,max_day
            min_max_set = set()
            min_max_set.add(min(v['total_diff_rate'].keys()))
            min_max_set.add(max(v['total_diff_rate'].keys()))
            for column, info in v['column_diff_rate'].items():
                min_max_set.add(min(info.keys()))
                min_max_set.add(max(info.keys()))
            min_day, max_day = min(min_max_set), max(min_max_set)

            # 1.删掉数据库中【所有】指标相应周期的数据（data中的指标最小和最大账期之间的数据,以及小于sixtyDaysAgo的账期数据），然后更新。
            # 删除数据库中需要更新的总记录数差异记录
            day_total_exists = list(table.table_data.setdefault('total_diff_rate', {}).keys())
            for day in day_total_exists:
                if min_day <= day <= max_day or day < sixtyDaysAgo:
                    del table.table_data['total_diff_rate'][day]
            # 删除数据库中需要更新的指标差异记录
            for column, info in table.table_data.setdefault('column_diff_rate', {}).items():
                day_column_exists = list(info.keys())
                for day in day_column_exists:
                    if min_day <= day <= max_day or day < sixtyDaysAgo:
                        del table.table_data['column_diff_rate'][column][day]

            # 更新
            table.table_data['total_diff_rate'].update(v['total_diff_rate'])
            for column,info in v['column_diff_rate'].items():
                table.table_data['column_diff_rate'].setdefault(column,{}).update(info)
            table.save()
        return HttpResponse('Ok')
    except Exception as e:
        print(e)
        return HttpResponse('No')


def do_once(request):
    try:
        data = get_dep()
        for key, v in data.items():
            table = TableDependence.objects.get(table_name=key) if TableDependence.objects.filter(
                table_name=key) else TableDependence(
                table_name=key)

            table.dependence = v
            table.save()
        return HttpResponse('Ok')
    except Exception as e:
        print(e)
        return HttpResponse('No')


@is_authenticated
def drawtable(request):
    json_data = request.body.decode('utf-8')
    info = json.loads(json_data)
    table_name = info.get('table_name', '').strip()

    # line_path = 'mycharts/render/tabledata/charts_%s.html' % table_name.split('.')[1]
    # 部署到apache服务器后需要使用绝对路径
    line_path = os.path.join(app_dir, 'render/tabledata/charts_%s.html' % table_name.split('.')[1])
    if not os.path.exists(line_path) or time.time() - os.path.getmtime(line_path) > 86400:
        table = get_object_or_404(TableData, table_name=table_name)
        line_name = table.table_name
        table_data = table.table_data
        x_data = table_data.get("total_diff_rate").keys()
        y_data = table_data.get("total_diff_rate").values()
        line = (
            charts.Line()
                .set_global_opts(
                tooltip_opts=opts.TooltipOpts(is_show=True),
                xaxis_opts=opts.AxisOpts(type_="category"),
                yaxis_opts=opts.AxisOpts(
                    type_="value",
                    axistick_opts=opts.AxisTickOpts(is_show=True),
                    splitline_opts=opts.SplitLineOpts(is_show=True),

                ),
                title_opts=opts.TitleOpts(title="差异比", subtitle="单位1")
            )
                .add_xaxis(xaxis_data=x_data)
                .add_yaxis(
                series_name=line_name,
                y_axis=y_data,
                symbol="circle",
                itemstyle_opts=opts.ItemStyleOpts(border_color='#fff'),
                markpoint_opts=opts.MarkPointOpts(
                    label_opts=opts.LabelOpts(color='#fff'),
                    data=[opts.MarkPointItem(type_='max', name='最大值'), opts.MarkPointItem(type_='min', name='最小值'),
                          opts.MarkLineItem(type_="average", name="平均值")]

                ),
                markline_opts=opts.MarkLineItem(type_='average'),
                is_symbol_show=True,
                label_opts=opts.LabelOpts(is_show=False),
                is_connect_nones=True
            )
        )
        line.render(line_path)

    chart = open(line_path).read()
    return HttpResponse(chart)


@is_authenticated
def drawtable_detail(request):
    #  time.sleep(0.1)  # 测试前端用户感知
    json_data = request.body.decode('utf-8')
    info = json.loads(json_data)
    table_name = info.get('table_name', '').strip()
    JSFUNC = """<span style='color:yellow;font-size:20px'>节点<span>
     <span style='color:red;font-size:30px'>{line}<br>------<span>"""  # { 图表的名字 line } 或者{ @[index] }
    # line_path = 'mycharts/render/tabledata/charts_%s.html' % table_name.split('.')[1]
    # 部署到apache服务器后需要使用绝对路径
    line_path = os.path.join(app_dir, 'render/tabledata/charts_%s.html' % table_name.split('.')[1])
    if not os.path.exists(line_path) or time.time() - os.path.getmtime(line_path) > 60:
        table = get_object_or_404(TableData, table_name=table_name)
        line_name = table.table_name
        table_data = table.table_data
        x_data = table_data.get("total_diff_rate").keys()
        y_data = table_data.get("total_diff_rate").values()

mysite/mycharts/templates/mycharts/detail.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hello {{ name }}</title>
    <!--    <style type='text/css'>
            body {color: slategrey;background: lavender}
            #submit {color: red;background: lightblue;b}

        </style>
    -->
    <link rel="shortcut icon" href="{% static 'images/bilibili.ico' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{% static '/css/sweetalert.css' %}">
    <script type="text/javascript" src="{% static '/js/sweetalert.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static '/css/alert_box.css' %}">
    <script type="text/javascript" src="{% static '/js/my_alert.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
<h1> Yo,Hello! </h1>

<script type="text/javascript">

    {% if isVoted %}
        {% if Duplicate_Submission %}
            swal('You have voted for {{ question.id }}-{{ voted_choice }}')
        {% elif isSuccessful %}
            swal('Thanks for voting {{ question.id }}-{{ voted_choice }}')
        {% else %}
            swal('You failed to vote. Please try again later:{{ voted_question.id }}-{{ voted_choice }}')
        {% endif %}

    {% endif %}

</script>
</body>
<div id="question_detail">
    <h2>The detail of Questions</h2>
    <input type="button" class="blue_btn" value="返回列表" onclick="javascript:window.location.href='/polls/'"/>
    <div>
        <h2> {{ question.id }}.{{ question.question_text }} </h2>
        <th>
            {% for choice in choices %}

                <td>当前投票：{{ choice.choice_text }}:</td>
                <td>{{ choice.votes }}</td>


                <form style="display: inline" method="post" action="/polls/{{ question.id }}/">
                    {% csrf_token %}
                    <input type="hidden" name="choice_id" value="{{ choice.id }}">
                    <input value="vote" type="submit" id="submits">


                </form>


                <br/>
            {% endfor %}
        </th>
    </div>


</div>
</html>

mysite/mycharts/templates/mycharts/drawing.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>hello {{ name }}</title>
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="styleSheet" href="{% static 'css/audio.css' %}" type="text/css">
    <link rel="styleSheet" href="{% static 'css/index.css' %}" type="text/css">
    <script src="{%  static 'js/audio.js'%}"></script>
    <style type="text/css">
    .rt{
    width:auto;
    height:0;
    position:absolute;
    top:20px;
    right:10px;
    }
    .question:hover{color:red}



    </style>

</head>

<body>
<h1> Yo,Hello! </h1>
<input type="button" class="blue_btn" value="返回列表" onclick="javascript:window.location.href='/polls/'"/>

<div class="rt">

    <span>
        <form action="/polls/logout/" method="post">
        <input type="submit" value="{{ name}}登出">
    </form>
    </span>

</div>


<p>
<H1>Questions List</H1></p>


<div>

    {% if latest_question_list %}
    {% csrf_token %}
    <ul>
        {% for question in latest_question_list %}

        <li class="question" value="{{ question.id}}" style="cursor:hand">{{ question.question_text }} </li>

        {% endfor %}
    </ul>

    {% else %}
    <p>There is no polls </p>
    {% endif %}

</div>
<p>
<div id="drawing"></div>
</p>
<script type="text/javascript" src="{% static 'js/echarts.min.js' %}"></script>
<script type="text/javascript">
        	$('.question').click(function () {
        	    var csrf =$("input[name='csrfmiddlewaretoken']").val()
                var question_id = $(this).val()

		        $.ajax({
				  url:  '/polls/drawing/'+question_id,
				  type: 'get',
				  async: false,
				  timeout: 4000,
				  headers:{'X-CSRFtoken':csrf},
				  processData: false,// 告诉jQuery不要去处理发送的数据
				  contentType: false,// 告诉jQuery不要去设置Content-Type请求头
				  beforeSend: function () {//过程...
				      console.log('正在进行，请稍候')

				  },
				  success: function (res) {
                            $("#drawing").html(res);
				   },

				   error:function(){
				   		console.log('404')
				   }
				})
			})





</script>
</body>
</html>

mysite/mycharts/templates/mycharts/hello.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hello {{ name }}</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'images/bilibili.ico' %}" type="image/x-icon">
    <link rel="styleSheet" href="{% static 'css/index.css' %}" type="text/css">
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
<h1> Yo,Hello! </h1>
    <input type="button" class="blue_btn" value="返回列表" onclick="javascript:window.location.href='/polls/'"/>

</body>
<form action="/polls/touch/" method="post">
<input type="submit" value="Touch Me">

</form>
</html>

mysite/mycharts/templates/mycharts/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=9"/>
    <meta http-equiv="X-UA-Compatible" content="IE=10"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >
    <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
    <title>hello {{ name }}</title>
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{%  static 'js/audio.js'%}"></script>
    <!--{% load static %} -->

</head>

<body>
<!--<div>-->
<!--    <input type="button" class="resttest" value="get">-->
<!--    <input type="button" class="resttest" value="put">-->
<!--    <input type="button" class="resttest" value="delete">-->
<!--    <input type="button" class="resttest" value="post">-->
<!--    <input type="button" class="resttest" value="zidingyi">-->
<!--</div>-->
<!--<div id="showMethod">showMethod</div>-->
<style type="text/css">
    .rt{
    width:auto;
    height:0;
    position:absolute;
    top:20px;
    right:10px;
    }

    #showing{
    width:auto;
    height:auto;
    position:absolute;
    left:20px;
    bottom:auto;
    }
    .table_name:hover{color:blue}

    #drawing{
    width:auto;
    height:auto;
    position:absolute;
    left:auto;
    bottom:10px;
    right:10px
    }




</style>
<h1> Yo,Hello! </h1>
<p>
<div class="rt">

    <span>
        <form action="logout/" method="post">
        <input type="submit" value="{{name}}:登出" align="right">
    </form>
    </span>

</div>
</p>

<p>
<H1>Table List</H1>
</p>
<input type="search" id="find_str" placeholder="查询的表名"><input type="button" value="查询" id="search">
<div id="showing">
    <form>
        {% csrf_token %}

        <ul>
            {% for table in tables %}
            <li class="table_name" style="cursor:hand" value="1"> {{ table.table_name }}</li>

            {% endfor %}

        </ul>

    </form>
</div>

<script type="text/javascript" src="{% static 'js/echarts.min.js' %}"></script>
<script type="text/javascript">

        	    $('#search').click(function () {
        	    this_button = $(this)
                this_button.attr("disabled",true);
                var csrf =$("input[name='csrfmiddlewaretoken']").val()
                var find_str =$('#find_str').val()
		        $.ajax({
				  url:  '{% url 'mycharts:searchtable'%}',
				  type: 'POST',
				  async: true,
				  traditional:true,
				  headers:{'X-CSRFtoken':csrf},
				  data: JSON.stringify({'find_str':find_str}),
				  processData: false,// 告诉jQuery不要去处理发送的数据
				  contentType: false,// 告诉jQuery不要去设置Content-Type请求头
				  beforeSend: function() {//过程...
                    $("#showing").html('正在查询...');
				  },
				  complete : function ()
				  {
                this_button.attr("disabled",false);
				  },
				  success: function (res) {

                          $("#showing").html(res);


				   },
				   error:function(){
				   		console.log('404')
				   }
				})


			})
;

        	    $('.table_name').click(function () {
        	    this_button = $(this)
                this_button.attr("disabled",true);
                var csrf =$("input[name='csrfmiddlewaretoken']").val()
                var table_name =this_button.text()

		        $.ajax({
				  url:  '{% url 'mycharts:drawtable' %}',
				  type: 'POST',
				  async: true,//ajax的async设置为false时浏览器的渲染(UI)线程和js线程是互斥的，所以修改ui的beforeSend是不会生效的。
				  traditional:true,
				  timeout:4000,
				  headers:{'X-CSRFtoken':csrf},
				  data: JSON.stringify({'table_name':table_name}),
				  processData: false,// 告诉jQuery不要去处理发送的数据
				  contentType: false,// 告诉jQuery不要去设置Content-Type请求头
				  beforeSend: function() {//过程...
                    $("#drawing").html('<H1 >Drawing...</H1>');
				  },
				  complete : function ()
				  {

				  },
				  success: function (res) {

                          $("#drawing").html(res);

				   },
				   error:function(){
				   		console.log('404')
				   },
				   				   　　complete : function(XMLHttpRequest,status){ //请求完成后最终执行参数
 　　　                　if(status=='timeout'){//超时,status还有success,error等值的情况
                     $("#drawing").html("请求响应超时");

            　　　　}
            　　}
				})

			   setTimeout(function(){
                this_button.attr("disabled",false);
                }, 1000);

			})


</script>
<div id="drawing"></div>
</body>
</html>

mysite/mycharts/templates/mycharts/login.html
{% load static  %}


<html lang="en">
<head>

<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta http-equiv="X-UA-Compatible" content="IE=10"/>

<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
    <meta charset="UTF-8">
    <title>hello
        {% if name  %}
    name
        {% else  %}
        man
        {% endif %}

    </title>
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="styleSheet" href="{% static '/css/login.css' %}" type="text/css">
    <!--{% load static %} -->
    <link rel="shortcut icon" href="{% static 'images/bilibili.ico' %}" type="image/x-icon">

</head>
<body>
<h1> Yo,Hello! </h1>
</body>
<form   action="/mycharts/login/" method="post">{% csrf_token %}
    <div>
        <label for="user_name">Your name: </label>
        <input id="user_name" type="text" name="user" placeholder="用户名">
    </div>
    <div>
        <label for="user_name">Your password: </label>
        <input type="text" name='passwd' id="passwd" placeholder="Your password:">
        <input type="submit" value="login">
		<input type="button" id="register" value="注册账号"/>
    </div>
</form>
<div id="inner_register"></div>
<script type="text/javascript">
        	$('#register').click(function () {

		        $.ajax({
				  url:  '/polls/register/',
				  type: 'get',
				  async: false,
				  data: null,
				  processData: false,// 告诉jQuery不要去处理发送的数据
				  contentType: false,// 告诉jQuery不要去设置Content-Type请求头
				  beforeSend: function () {//过程...
				      console.log('正在进行，请稍候')
				  },
				  success: function (res) {
                            $("#inner_register").html(res);
				   },
				   error:function(){
				   		console.log('404')
				   }
				})
			})
</script>
</html>

mysite/mycharts/templates/mycharts/register.html
{% load static  %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hello
        {% if name  %}
    name
        {% else  %}
        human
        {% endif %}

    </title>
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="styleSheet" href="{% static '/css/login.css' %}" type="text/css">
    <script type="text/javascript" src="{% static '/js/sweetalert.js' %}"></script>
    <link rel="shortcut icon" href="{% static 'images/bilibili.ico' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{% static '/css/sweetalert.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/alert_box.css' %}">
    <script type="text/javascript" src="{% static '/js/my_alert.js' %}"></script>
</head>
<body>
<script type="text/javascript">
    {% if failed %}
        {% if duplicate_user_name %}
            swal('用户名已被使用')
        {% elif just_failed %}
            swal('用户名或密码不符合规则')
        {% endif %}
    {% endif %}
</script>
<h1> Yo,Hello! </h1>
</body>
<form   action="/polls/register/" method="post">
    {% csrf_token %}
    <div>
        <label for="user_name">Your name: </label>
        <input id="user_name" type="text" name="user_name" placeholder="用户名">
    </div>
    <div>
        <label for="user_name">Your password: </label>
        <input type="text" name='passwd' id="passwd" placeholder="any words">
        <input type="submit" value="register">
    </div>
</form>

</html>